package handlers

import (
	"context"
	"crypto/sha256"
	"fmt"
	"log/slog"
	"net/http"
	"strings"
	"time"

	"github.com/crewjam/saml/samlsp"
	"github.com/gin-gonic/gin"
	"github.com/openincident/openincident/internal/api/middleware"
	appredis "github.com/openincident/openincident/internal/redis"
	"github.com/openincident/openincident/internal/services"
)

const (
	// Per-account lockout: 5 failures within 15 minutes triggers a 15-minute lockout.
	loginMaxFailures      = 5
	loginFailureWindowSec = 15 * 60
	loginLockoutSec       = 15 * 60
)

// setSessionCookie writes the oi_session cookie with SameSite=Strict.
// Gin's c.SetCookie does not support SameSite selection, so we write directly.
func setSessionCookie(c *gin.Context, token string, maxAge int) {
	http.SetCookie(c.Writer, &http.Cookie{
		Name:     "oi_session",
		Value:    token,
		MaxAge:   maxAge,
		Path:     "/",
		HttpOnly: true,
		Secure:   middleware.IsSecure(),
		SameSite: http.SameSiteStrictMode,
	})
}

// Logout handles GET /auth/logout — browser redirect flow (kept for backwards compatibility).
func Logout(samlMiddleware *samlsp.Middleware, localAuth services.LocalAuthService) gin.HandlerFunc {
	return func(c *gin.Context) {
		slog.Info("auth: logout", "ip", c.ClientIP())
		clearSession(c, samlMiddleware, localAuth)
		c.Redirect(http.StatusFound, "/login")
	}
}

// APILogout handles POST /api/v1/auth/logout — called from the SPA via fetch.
// Returns JSON so the frontend can handle navigation itself.
func APILogout(samlMiddleware *samlsp.Middleware, localAuth services.LocalAuthService) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Header("Cache-Control", "no-store")
		slog.Info("auth: logout", "ip", c.ClientIP())
		clearSession(c, samlMiddleware, localAuth)
		c.JSON(http.StatusOK, gin.H{"ok": true})
	}
}

// clearSession invalidates the current session for both local and SAML auth.
func clearSession(c *gin.Context, samlMiddleware *samlsp.Middleware, localAuth services.LocalAuthService) {
	if localAuth != nil {
		if cookie, err := c.Cookie("oi_session"); err == nil {
			_ = localAuth.Logout(cookie)
		}
		setSessionCookie(c, "", -1)
	}
	if samlMiddleware != nil {
		_ = samlMiddleware.Session.DeleteSession(c.Writer, c.Request)
	}
}

// Login handles POST /api/v1/auth/login — email/password authentication.
func Login(localAuth services.LocalAuthService) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Header("Cache-Control", "no-store")

		var req struct {
			Email    string `json:"email"    binding:"required,email"`
			Password string `json:"password" binding:"required,min=1"`
		}
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": gin.H{"code": "invalid_request", "message": err.Error()}})
			return
		}

		// Per-account lockout check — keyed on a hash of the email to avoid PII in Redis.
		if isAccountLocked(req.Email) {
			slog.Warn("auth: login rejected — account locked out", "ip", c.ClientIP())
			c.Header("Retry-After", fmt.Sprintf("%d", loginLockoutSec))
			c.JSON(http.StatusTooManyRequests, gin.H{"error": gin.H{
				"code":    "account_locked",
				"message": "Too many failed login attempts. Try again later.",
			}})
			return
		}

		session, err := localAuth.Login(req.Email, req.Password)
		if err != nil {
			recordLoginFailure(req.Email)
			slog.Warn("auth: login failed", "ip", c.ClientIP())
			c.JSON(http.StatusUnauthorized, gin.H{"error": gin.H{"code": "unauthorized", "message": err.Error()}})
			return
		}

		clearLoginFailures(req.Email)
		slog.Info("auth: login success", "ip", c.ClientIP())

		// Set session cookie: 7-day, HttpOnly, SameSite=Strict
		setSessionCookie(c, session.Token, 7*24*3600)
		c.JSON(http.StatusOK, gin.H{"ok": true})
	}
}

// SetupTokenLogin handles POST /api/v1/auth/login/setup-token.
// Exchanges a one-time setup token (generated by CreateUser or ResetPassword)
// for a live session cookie so the recipient of an invite link is logged in
// immediately without needing to know the password.
func SetupTokenLogin(localAuth services.LocalAuthService) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Header("Cache-Control", "no-store")
		var req struct {
			Token string `json:"token" binding:"required"`
		}
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": gin.H{"code": "invalid_request", "message": err.Error()}})
			return
		}
		// GetSessionUser validates the token exists and is not expired.
		if _, err := localAuth.GetSessionUser(req.Token); err != nil {
			c.JSON(http.StatusUnauthorized, gin.H{"error": gin.H{"code": "unauthorized", "message": "Setup link is invalid or has expired"}})
			return
		}
		setSessionCookie(c, req.Token, 7*24*3600)
		slog.Info("auth: setup-token login", "ip", c.ClientIP())
		c.JSON(http.StatusOK, gin.H{"ok": true})
	}
}

// GetCurrentUser handles GET /api/v1/auth/me.
func GetCurrentUser(localAuth services.LocalAuthService, samlConfigured bool) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Header("Cache-Control", "no-store")

		// Local session user resolved by RequireAuth or InjectSAMLSession middleware.
		if user := middleware.GetLocalUser(c); user != nil {
			c.JSON(http.StatusOK, gin.H{
				"authenticated": true,
				"id":            user.ID,
				"email":         user.Email,
				"name":          user.Name,
				"role":          user.Role,
				"ssoEnabled":    samlConfigured,
			})
			return
		}

		// /auth/me is public (no RequireAuth), so local session cookies are not
		// resolved by middleware. Check the cookie directly here.
		if localAuth != nil {
			if cookie, err := c.Cookie("oi_session"); err == nil && cookie != "" {
				if user, err := localAuth.GetSessionUser(cookie); err == nil {
					c.JSON(http.StatusOK, gin.H{
						"authenticated": true,
						"id":            user.ID,
						"email":         user.Email,
						"name":          user.Name,
						"role":          user.Role,
						"ssoEnabled":    samlConfigured,
					})
					return
				}
			}
		}

		// Fallback: SAML session exists but DB resolution failed (e.g. deactivated user).
		// Return minimal info — no id/role since those require a DB record.
		if session := middleware.GetSAMLSession(c); session != nil {
			if claims, ok := session.(samlsp.JWTSessionClaims); ok {
				c.JSON(http.StatusOK, gin.H{
					"authenticated": true,
					"email":         claims.Attributes.Get("email"),
					"name":          claims.Attributes.Get("displayName"),
					"ssoEnabled":    true,
				})
				return
			}
			c.JSON(http.StatusOK, gin.H{"authenticated": true, "ssoEnabled": true})
			return
		}

		// Determine true open mode: only when no users exist AND SAML is not configured.
		// Once a local user has been created, login is always required.
		isOpenMode := !samlConfigured
		if isOpenMode && localAuth != nil {
			count, err := localAuth.CountUsers()
			if err == nil && count > 0 {
				isOpenMode = false
			}
		}

		if isOpenMode {
			c.JSON(http.StatusOK, gin.H{
				"authenticated": false,
				"mode":          "open",
				"ssoEnabled":    false,
				"message":       "No auth configured — all requests permitted",
			})
		} else {
			c.JSON(http.StatusOK, gin.H{
				"authenticated": false,
				"ssoEnabled":    samlConfigured,
			})
		}
	}
}

// emailHash returns a short non-reversible identifier for use in Redis keys.
// Using the first 8 bytes of SHA-256 keeps keys compact while avoiding PII.
func emailHash(email string) string {
	h := sha256.Sum256([]byte(strings.ToLower(strings.TrimSpace(email))))
	return fmt.Sprintf("%x", h[:8])
}

func isAccountLocked(email string) bool {
	if appredis.Client == nil {
		return false
	}
	ctx, cancel := context.WithTimeout(context.Background(), 200*time.Millisecond)
	defer cancel()
	key := fmt.Sprintf("lockout:login:%s", emailHash(email))
	exists, err := appredis.Client.Exists(ctx, key).Result()
	return err == nil && exists > 0
}

func recordLoginFailure(email string) {
	if appredis.Client == nil {
		return
	}
	ctx, cancel := context.WithTimeout(context.Background(), 200*time.Millisecond)
	defer cancel()
	failKey := fmt.Sprintf("failed:login:%s", emailHash(email))
	count, err := appredis.Client.Incr(ctx, failKey).Result()
	if err != nil {
		return
	}
	// Set TTL on first failure; subsequent increments reuse the existing window.
	if count == 1 {
		appredis.Client.Expire(ctx, failKey, loginFailureWindowSec*time.Second)
	}
	if count >= loginMaxFailures {
		lockKey := fmt.Sprintf("lockout:login:%s", emailHash(email))
		appredis.Client.Set(ctx, lockKey, "1", loginLockoutSec*time.Second)
	}
}

func clearLoginFailures(email string) {
	if appredis.Client == nil {
		return
	}
	ctx, cancel := context.WithTimeout(context.Background(), 200*time.Millisecond)
	defer cancel()
	failKey := fmt.Sprintf("failed:login:%s", emailHash(email))
	appredis.Client.Del(ctx, failKey)
}
