apiVersion: v1
entries:
  fluidify-regen:
  - apiVersion: v2
    appVersion: 0.11.0
    created: "2026-05-19T09:24:23.564628589Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: '>=16.0.0 <20.0.0'
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: '>=21.0.0 <27.0.0'
    description: Fluidify Regen — open-source incident management platform
    digest: 9bf2b91ff4647b92d81c393a2baa093f00452d84ea08c818d2c4741a66fa0196
    home: https://github.com/FluidifyAI/Regen
    keywords:
    - incident-management
    - on-call
    - alerting
    maintainers:
    - name: Fluidify Contributors
    name: fluidify-regen
    sources:
    - https://github.com/FluidifyAI/Regen
    type: application
    urls:
    - https://charts.fluidify.ai/charts/fluidify-regen-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: 0.10.0
    created: "2026-05-19T09:24:23.552800835Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: '>=16.0.0 <20.0.0'
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: '>=21.0.0 <27.0.0'
    description: Fluidify Regen — open-source incident management platform
    digest: 63a00c5bedbefcd85d4f24a2c0af7605efbded06b05d892349c7aa155a085ff4
    home: https://github.com/FluidifyAI/Regen
    keywords:
    - incident-management
    - on-call
    - alerting
    maintainers:
    - name: Fluidify Contributors
    name: fluidify-regen
    sources:
    - https://github.com/FluidifyAI/Regen
    type: application
    urls:
    - https://charts.fluidify.ai/charts/fluidify-regen-0.1.0.tgz
    version: 0.1.0
generated: "2026-05-19T09:24:23.541474433Z"
