apiVersion: v1
entries:
  fluidify-regen:
  - apiVersion: v2
    appVersion: 0.11.0
    created: "2026-05-01T03:56:08.104890301Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: '>=16.0.0 <20.0.0'
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: '>=21.0.0 <27.0.0'
    description: Fluidify Regen — open-source incident management platform
    digest: 5a45b2152b1e4b79d331e0566e23dc207f8b7a6443cb10f9645897767b1a61a7
    home: https://github.com/FluidifyAI/Regen
    keywords:
    - incident-management
    - on-call
    - alerting
    maintainers:
    - name: Fluidify Contributors
    name: fluidify-regen
    sources:
    - https://github.com/FluidifyAI/Regen
    type: application
    urls:
    - https://charts.fluidify.ai/charts/fluidify-regen-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: 0.10.0
    created: "2026-05-01T03:56:08.092745482Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: '>=16.0.0 <20.0.0'
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: '>=21.0.0 <27.0.0'
    description: Fluidify Regen — open-source incident management platform
    digest: 63a00c5bedbefcd85d4f24a2c0af7605efbded06b05d892349c7aa155a085ff4
    home: https://github.com/FluidifyAI/Regen
    keywords:
    - incident-management
    - on-call
    - alerting
    maintainers:
    - name: Fluidify Contributors
    name: fluidify-regen
    sources:
    - https://github.com/FluidifyAI/Regen
    type: application
    urls:
    - https://charts.fluidify.ai/charts/fluidify-regen-0.1.0.tgz
    version: 0.1.0
generated: "2026-05-01T03:56:08.079748227Z"
