/**
 * LoginPage — shown when the user has no active session.
 *
 * - Always shows a local email/password form.
 * - Shows the SSO button only when ssoEnabled=true (SAML configured on server).
 * - In open-access mode (no auth configured) this page is never rendered.
 *
 * Design: cohesive with the app's dark navy (#0F172A) + blue (#2563EB) identity.
 * Background uses a CSS dot-grid for depth without adding visual noise.
 */
import { useState, useEffect } from 'react'
import { login, bootstrap, exchangeSetupToken } from '../api/auth'
import { useAuth } from '../hooks/useAuth'

// Returns the post-login destination: the ?next= param if present and safe,
// otherwise the app root. Prevents open-redirect by only accepting same-origin paths.
function postLoginRedirect(): string {
  const params = new URLSearchParams(window.location.search)
  const next = params.get('next')
  if (next && next.startsWith('/') && !next.startsWith('//')) {
    return next
  }
  return '/'
}

export function LoginPage() {
  const { ssoEnabled, openMode, loading: authLoading } = useAuth()

  // Sign-in form state
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  // Consume a one-time setup token from the URL (?setup=<token>).
  // Generated by admin invite or password reset — auto-logs the user in.
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const token = params.get('setup')
    if (!token) return
    exchangeSetupToken(token)
      .then(() => { window.location.href = postLoginRedirect() })
      .catch(() => setError('This setup link has expired or has already been used.'))
  }, [])

  // First-time setup form state — auto-open when no accounts exist yet
  const [showSetup, setShowSetup] = useState(openMode)
  const [setupName, setSetupName] = useState('')
  const [setupEmail, setSetupEmail] = useState('')
  const [setupPassword, setSetupPassword] = useState('')
  const [setupError, setSetupError] = useState('')
  const [setupLoading, setSetupLoading] = useState(false)

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setError('')
    setLoading(true)
    try {
      await login({ email, password })
      window.location.href = postLoginRedirect()
    } catch {
      setError('Invalid email or password')
    } finally {
      setLoading(false)
    }
  }

  async function handleSetup(e: React.FormEvent) {
    e.preventDefault()
    setSetupError('')
    setSetupLoading(true)
    try {
      await bootstrap({ name: setupName, email: setupEmail, password: setupPassword })
      // Bootstrap succeeded — immediately log in with the new credentials
      await login({ email: setupEmail, password: setupPassword })
      window.location.href = '/'
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err)
      if (msg.includes('409') || msg.includes('already exist')) {
        setSetupError('An admin account already exists. Sign in above.')
      } else if (msg.includes('8')) {
        setSetupError('Password must be at least 8 characters.')
      } else {
        setSetupError('Setup failed. Check your details and try again.')
      }
    } finally {
      setSetupLoading(false)
    }
  }

  return (
    <div
      className="min-h-screen bg-[#0F172A] flex items-center justify-center p-4"
      style={{
        backgroundImage: `radial-gradient(circle, #1E293B 1px, transparent 1px)`,
        backgroundSize: '28px 28px',
      }}
    >
      {/* Subtle ambient glow behind the card */}
      <div
        className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 rounded-full pointer-events-none"
        style={{
          background: 'radial-gradient(circle, rgba(37,99,235,0.08) 0%, transparent 70%)',
        }}
      />

      <div className="relative w-full max-w-sm">
        {/* Card */}
        <div
          className="rounded-2xl border border-[#1E293B] bg-[#0F172A] p-10"
          style={{ boxShadow: '0 0 0 1px #1E293B, 0 24px 48px rgba(0,0,0,0.4)' }}
        >
          {/* Logo + wordmark */}
          <div className="flex flex-col items-center mb-10">
            <div className="relative mb-5">
              {/* Outer ring */}
              <div className="absolute inset-0 rounded-full border border-[#2563EB] opacity-20 scale-150" />
              {/* Icon container */}
              <div className="w-14 h-14 rounded-xl bg-[#1E3A5F] flex items-center justify-center border border-[#2563EB] border-opacity-30">
                <ShieldIcon className="w-7 h-7 text-[#2563EB]" />
              </div>
            </div>

            <h1 className="text-[#F1F5F9] text-xl font-semibold tracking-tight">
              OpenIncident
            </h1>
            <p className="text-[#475569] text-sm mt-1">
              {openMode ? 'Set up your instance' : 'Incident management, self-hosted'}
            </p>
          </div>

          {/* Divider */}
          <div className="border-t border-[#1E293B] mb-8" />

          {/* In open mode (no accounts yet), skip the login form — nothing to log in to */}
          {openMode && (
            <p className="text-[#475569] text-sm text-center mb-6">
              No accounts exist yet. Create the admin account below to get started.
            </p>
          )}

          {/* Local email/password form — hidden when no accounts exist */}
          <form onSubmit={handleSubmit} className={`space-y-4 ${openMode ? 'hidden' : ''}`} noValidate>
            <div className="space-y-3">
              <div>
                <label htmlFor="email" className="block text-[#94A3B8] text-xs font-medium mb-1.5">
                  Email
                </label>
                <input
                  id="email"
                  type="email"
                  autoComplete="email"
                  required
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="you@example.com"
                  className="w-full h-10 rounded-lg bg-[#1E293B] border border-[#334155] text-[#F1F5F9] text-sm px-3 placeholder-[#475569] focus:outline-none focus:ring-2 focus:ring-[#2563EB] focus:border-transparent transition-colors duration-150"
                />
              </div>

              <div>
                <label htmlFor="password" className="block text-[#94A3B8] text-xs font-medium mb-1.5">
                  Password
                </label>
                <input
                  id="password"
                  type="password"
                  autoComplete="current-password"
                  required
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="••••••••"
                  className="w-full h-10 rounded-lg bg-[#1E293B] border border-[#334155] text-[#F1F5F9] text-sm px-3 placeholder-[#475569] focus:outline-none focus:ring-2 focus:ring-[#2563EB] focus:border-transparent transition-colors duration-150"
                />
              </div>
            </div>

            {/* Inline error */}
            {error && (
              <p className="text-[#F87171] text-sm text-center" role="alert">
                {error}
              </p>
            )}

            <button
              type="submit"
              disabled={loading}
              className="flex items-center justify-center gap-2.5 w-full h-11 rounded-lg bg-[#2563EB] hover:bg-[#1D4ED8] disabled:opacity-50 disabled:cursor-not-allowed text-white text-sm font-medium transition-colors duration-150 focus:outline-none focus:ring-2 focus:ring-[#2563EB] focus:ring-offset-2 focus:ring-offset-[#0F172A]"
            >
              {loading ? 'Signing in…' : 'Sign in'}
            </button>
          </form>

          {/* SSO divider + button — shown only when SAML is configured */}
          {!authLoading && ssoEnabled && (
            <>
              <div className="flex items-center gap-3 my-6">
                <div className="flex-1 border-t border-[#1E293B]" />
                <span className="text-[#334155] text-xs">or</span>
                <div className="flex-1 border-t border-[#1E293B]" />
              </div>

              <a
                href="/saml/login"
                className="flex items-center justify-center gap-2.5 w-full h-11 rounded-lg border border-[#334155] bg-transparent hover:bg-[#1E293B] text-[#94A3B8] hover:text-[#CBD5E1] text-sm font-medium transition-colors duration-150 focus:outline-none focus:ring-2 focus:ring-[#2563EB] focus:ring-offset-2 focus:ring-offset-[#0F172A]"
              >
                <KeyIcon className="w-4 h-4" />
                Sign in with SSO
              </a>
            </>
          )}

          {/* First-time setup section */}
          <div className={openMode ? '' : 'mt-6'}>
            {/* Toggle is only shown when there ARE existing accounts (open mode hides it) */}
            {!openMode && (
              <div className="flex items-center gap-3 mb-4">
                <div className="flex-1 border-t border-[#1E293B]" />
                <button
                  type="button"
                  onClick={() => { setShowSetup(!showSetup); setSetupError('') }}
                  className="text-[#475569] hover:text-[#94A3B8] text-xs transition-colors whitespace-nowrap"
                >
                  {showSetup ? 'Cancel setup' : 'First time here? Create admin account →'}
                </button>
                <div className="flex-1 border-t border-[#1E293B]" />
              </div>
            )}

            {showSetup && (
              <form onSubmit={handleSetup} className="space-y-3" noValidate>
                <div>
                  <label htmlFor="setup-name" className="block text-[#94A3B8] text-xs font-medium mb-1.5">
                    Full name
                  </label>
                  <input
                    id="setup-name"
                    type="text"
                    autoComplete="name"
                    required
                    value={setupName}
                    onChange={(e) => setSetupName(e.target.value)}
                    placeholder="Jane Smith"
                    className="w-full h-10 rounded-lg bg-[#1E293B] border border-[#334155] text-[#F1F5F9] text-sm px-3 placeholder-[#475569] focus:outline-none focus:ring-2 focus:ring-[#2563EB] focus:border-transparent transition-colors duration-150"
                  />
                </div>
                <div>
                  <label htmlFor="setup-email" className="block text-[#94A3B8] text-xs font-medium mb-1.5">
                    Email
                  </label>
                  <input
                    id="setup-email"
                    type="email"
                    autoComplete="email"
                    required
                    value={setupEmail}
                    onChange={(e) => setSetupEmail(e.target.value)}
                    placeholder="admin@example.com"
                    className="w-full h-10 rounded-lg bg-[#1E293B] border border-[#334155] text-[#F1F5F9] text-sm px-3 placeholder-[#475569] focus:outline-none focus:ring-2 focus:ring-[#2563EB] focus:border-transparent transition-colors duration-150"
                  />
                </div>
                <div>
                  <label htmlFor="setup-password" className="block text-[#94A3B8] text-xs font-medium mb-1.5">
                    Password <span className="text-[#475569] font-normal">(min. 8 characters)</span>
                  </label>
                  <input
                    id="setup-password"
                    type="password"
                    autoComplete="new-password"
                    required
                    minLength={8}
                    value={setupPassword}
                    onChange={(e) => setSetupPassword(e.target.value)}
                    placeholder="••••••••"
                    className="w-full h-10 rounded-lg bg-[#1E293B] border border-[#334155] text-[#F1F5F9] text-sm px-3 placeholder-[#475569] focus:outline-none focus:ring-2 focus:ring-[#2563EB] focus:border-transparent transition-colors duration-150"
                  />
                </div>

                {setupError && (
                  <p className="text-[#F87171] text-sm text-center" role="alert">
                    {setupError}
                  </p>
                )}

                <button
                  type="submit"
                  disabled={setupLoading}
                  className="flex items-center justify-center gap-2.5 w-full h-11 rounded-lg border border-[#2563EB] bg-transparent hover:bg-[#1E3A5F] disabled:opacity-50 disabled:cursor-not-allowed text-[#60A5FA] text-sm font-medium transition-colors duration-150 focus:outline-none focus:ring-2 focus:ring-[#2563EB] focus:ring-offset-2 focus:ring-offset-[#0F172A]"
                >
                  {setupLoading ? 'Creating account…' : 'Create admin account & sign in'}
                </button>
              </form>
            )}
          </div>

          {/* Footer note */}
          <p className="mt-6 text-center text-[#334155] text-xs">
            {openMode
              ? 'This account will have full admin access'
              : ssoEnabled
                ? 'Access is managed by your identity provider or local accounts'
                : 'Sign in with your OpenIncident credentials'}
          </p>
        </div>

        {/* Below-card help link */}
        <p className="text-center mt-6 text-[#334155] text-xs">
          Self-hosting?{' '}
          <a
            href="https://github.com/openincident/openincident"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#475569] hover:text-[#94A3B8] transition-colors underline underline-offset-2"
          >
            View documentation
          </a>
        </p>
      </div>
    </div>
  )
}

// ── Inline SVG icons (no extra deps) ────────────────────────────────────────

function ShieldIcon({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      strokeWidth={1.75}
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"
      />
    </svg>
  )
}

function KeyIcon({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      strokeWidth={2}
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M15.75 5.25a3 3 0 013 3m3 0a6 6 0 01-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1121.75 8.25z"
      />
    </svg>
  )
}
